config/routes.rb
KittRailsSample::Application.routes.draw do

  root to: 'pages#root'

  match 'sign_in'  => 'user_sessions#new',     as: :sign_in
  match 'sign_out' => 'user_sessions#destroy', as: :sign_out

  resources :user_sessions, only: [:new, :create, :destroy]

  match 'sign_up' => 'registrations#new',              via: :get,  as: :sign_up
  match 'sign_up' => 'registrations#create',           via: :post, as: :sign_up
  match 'activate/:token' => 'registrations#activate', via: :get,  as: :activation

  match 'forgotten_password' => 'password_resets#new',     via: :get,  as: :forgotten_password
  match 'forgotten_password' => 'password_resets#create',  via: :post, as: :forgotten_password
  match 'reset_password/:token' => 'password_resets#edit', via: :get,  as: :reset_password
  match 'reset_password/:id' => 'password_resets#update',  via: :put

  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can [:read, :update], User, id: user.id
    end

    # No one can destroy themselves.
    cannot :destroy, User, id: user.id


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name, :email, :password

  authenticates_with_sorcery!

  validates :name,
            presence: true,
            length: { maximum: 30 }

  validates :email,
            presence: true,
            email: true,
            uniqueness: true

  validates :password,
            presence: true,
            length: { minimum: 6 },
            if: :password

end

app/models/user_session.rb
class UserSession
  include ActiveAttr::BasicModel
  include ActiveAttr::MassAssignment

  attr_accessor :email, :password, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Uncomment to require auth on all actions (and opt-out when necessary).
  # before_filter :require_login, except: [:not_authenticated]

  protect_from_forgery
  check_authorization

  protected

  def not_authenticated
    redirect_to sign_in_path, alert: "Please sign in first."
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_authorization_check

  def root
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  skip_before_filter :require_login
  skip_authorization_check

  def create
    @user = User.find_by_email(params[:email])

    # Send an email to the user with instructions on how to reset their password.
    @user.deliver_reset_password_instructions! if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to sign_in_path, notice: "Password reset instructions have been sent to your email."
  end

  def edit
    @token = params[:token]
    @user = User.load_from_reset_password_token(@token)
    not_authenticated if !@user
  end

  def update
    @token = params[:token] # needed to render the form again in case of error
    @user = User.load_from_reset_password_token(@token)
    not_authenticated if !@user

    # Clear the temporary token and update the password.
    if @user.change_password!(params[:user][:password])
      redirect_to sign_in_path, notice: "Password was successfully updated."
    else
      render action: 'edit'
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  skip_authorization_check

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user]) # TODO Safe attributes

    if @user.save
      redirect_to sign_in_path, notice: "Thanks for signing up. Please check your email for activation instructions."
    else
      render action: 'new'
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:token]))
      @user.activate!
      auto_login @user
      redirect_to sign_in_path, notice: "Your account has been activated and you're now signed in. Enjoy!"
    else
      not_authenticated
    end
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_filter :require_login, except: [:destroy]
  skip_authorization_check

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])

    if @user = login(@user_session.email, @user_session.password, @user_session.remember_me)
      redirect_back_or_to :users, notice: "Successfully signed in."
    else
      flash.now[:alert] = "Sign in failed."
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to :sign_in, notice: "Signed out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_login

  load_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render action: 'new'
    end
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: "User was successfully updated."
    else
      render action: 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_class(alert_type)
    alert_type = {
      alert: 'error',
      notice: 'info'
    }.fetch(alert_type, alert_type.to_s)
    "alert-#{alert_type}"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Kitt Rails Sample
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  body id=(controller.controller_name) class=(controller.action_name)
    .wrapper
      .container
        header.navbar.navbar-fixed-top
          nav.navbar-inner
            .container
              .brand Kitt Rails Sample
              ul.nav.pull-right
                - if current_user
                  li.dropdown
                    a.dropdown-toggle href='#' data-toggle='dropdown'
                      = current_user.email
                      b.caret
                    ul.dropdown-menu
                      li= link_to 'Sign Out', sign_out_path
                - else
                  li= link_to 'Sign In', sign_in_path

        - flash.each do |name, msg|
          = content_tag :div, raw(msg), class: "alert #{alert_class(name)}"

        = yield

      .push

    footer
      .container
        p &copy; 2013 All rights reserved.

app/views/pages/root.html.slim
.hero-unit
  h1 Hello, world!

  p Welcome to your newly generated rails application...
  p Meander around the code to see what's been done for you. Many small, and a few not-so-small, customizations have been made.
  p Custom generator templates create views that are bootstrap compatible and specs that are factory-aware and follow best practices.
  p This application also includes authentication and an example of authorization (sign in as user@example.com / password).

  p: a.btn.btn-primary.btn-large href=sign_in_path Sign In

app/views/password_resets/edit.html.slim
.page-header
  h1 Reset Your Password

= simple_form_for(@user, url: reset_password_path(@user)) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email, disabled: true
    = f.input :password, label: 'New Password', required: true, autofocus: true
    = hidden_field_tag :token, @token

  .form-actions
    = f.button :submit, 'Reset Password', class: 'btn btn-primary'
    '
    = link_to 'Cancel', sign_in_path, class: 'btn'

app/views/password_resets/new.html.slim
.page-header
  h1 Password Reset

= form_tag(forgotten_password_path, method: :post) do
  .control-group
    = label_tag :email, nil, class: 'control-label'
    .controls
      = text_field_tag :email, nil, placeholder: 'joe@example.com'

  .form-actions
    = submit_tag 'Reset My Password', class: 'btn btn-primary'

app/views/user_sessions/new.html.slim
= simple_form_for(@user_session) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email, placeholder: 'jdoe@example.com', autofocus: true
    = f.input :password

  ul.unstyled
    li= link_to 'Sign Up', sign_up_path
    li= link_to 'Reset Password', forgotten_password_path

  .form-actions
    = f.button :submit, 'Sign In', class: 'btn btn-primary'

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email, autofocus: true
    = f.input :name

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    '
    = link_to 'Back', users_path, class: 'btn'

app/views/users/edit.html.slim
.page-header
  h1 Editing user

== render 'form'

app/views/users/index.html.slim
div.page-header
  h1 Listing users

table.table.table-striped
  thead
    tr
      th ID
      th Email
      th Name
      th Actions

  tbody
  - @users.each do |user|
    tr
      td= link_to_if can?(:show, user), user.id, user_path(user)
      td= user.email
      td= user.name
      td
        - if can? :edit, user
          = link_to 'Edit', edit_user_path(user), class: 'btn btn-mini'
          '
        - if can? :destroy, user
          = link_to 'Destroy', user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-mini btn-danger'

- if can? :create, User
  = link_to 'New User', new_user_path, class: 'btn btn-primary'

app/views/users/new.html.slim
.page-header
  h1 Create user

== render 'form'

app/views/users/show.html.slim
.page-header
  h1 User

dl
  dt Email
  dd= @user.email
  dt Name
  dd= @user.name

- if can?(:edit, @user)
  = link_to 'Edit', edit_user_path(@user), class: 'btn'
  '
= link_to 'Back', users_path, class: 'btn'

- if can?(:destroy, @user)
  '
  = link_to 'Destroy', user_path(@user), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'